### PR TITLE
Upgrade nettle to version 3.6

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge/nettle, this is ready.

**Comment by isuruf** [comment]
@erykoff, would you like to become a maintainer for this feedstock? Looks like this feedstock is abandoned

**Comment by erykoff** [comment]
Sure, why not.  (And I agree.)

**Pull request merged**
